server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  database:
    driver: mysql
    host: 127.0.0.1
    port: 33060
    database: user_service
    username: root
  redis:
    addr: 127.0.0.1:34701
    read_timeout: 0.2s
    write_timeout: 0.2s
trace:
  endpoint: http://localhost:14268/api/traces
  service_name: user-service
  sampler: 1.0
  batcher: jaeger
