server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  database:
    driver: mysql
    host: 127.0.0.1
    port: 33060
    database: user_service
    username: root
  redis:
    addr: 127.0.0.1:34701
    read_timeout: 0.2s
    write_timeout: 0.2s
trace:
  endpoint: http://localhost:14268/api/traces
  service_name: auth-service
  sampler: 1.0
  batcher: jaeger
email:
  sender_name: "用户系统"        # 邮件发件人显示名称
  sender_email: "noreply@example.com"  # 发件人邮箱地址
  support_email: "support@example.com" # 客服支持邮箱
  company_name: "您的公司名称"   # 公司名称
  app_name: "您的应用名称"       # 应用名称
